CREATE DATABASE IF NOT EXISTS `cpt103`
DEFAULT CHARACTER SET utf8mb4
DEFAULT COLLATE utf8mb4_general_ci;

USE `cpt103`;

-- DROP TABLE IF EXISTS `class`;
-- DROP TABLE IF EXISTS `student`;
-- DROP TABLE IF EXISTS `teacher`;

DROP TABLE IF EXISTS `class`, `student`, `teacher`;
SHOW TABLES;

CREATE TABLE IF NOT EXISTS `student`
(
`student_id` CHAR(6) BINARY NOT NULL DEFAULT "EMPTY",
`name` CHAR(50) BINARY NOT NULL DEFAULT "EMPTY",
`age` SMALLINT UNSIGNED DEFAULT 0,
CONSTRAINT `primary_id` PRIMARY KEY (`student_id`)
);

CREATE TABLE IF NOT EXISTS `teacher`
(
  `teacher_id` CHAR(6) BINARY NOT NULL PRIMARY KEY,
  `name` CHAR(50) BINARY NOT NULL DEFAULT "EMPTY"
);

SHOW TABLES;
